# Generated by Django 4.2.4 on 2023-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_room_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='media'),
        ),
    ]
